// typeAction.js
export const FETCH_PATIENT_REQUEST = 'FETCH_PATIENT_REQUEST';
export const FETCH_PATIENT_SUCCESS = 'FETCH_PATIENT_SUCCESS';
export const FETCH_PATIENT_FAILURE = 'FETCH_PATIENT_FAILURE';

export const DELETE_PATIENT_SUCCESS = 'DELETE_PATIENT_SUCCESS';
export const DELETE_PATIENT_FAILURE = 'DELETE_PATIENT_FAILURE';

export const POST_PATIENT_SUCCESS = 'POST_PATIENT_SUCCESS';
export const POST_PATIENT_FAILURE = 'POST_PATIENT_FAILURE';
// action creator

export const ADD_RDV_SUCCESS = 'ADD_RDV_SUCCESS';
export const UPDATE_RDV_SUCCESS = 'UPDATE_RDV_SUCCESS';
